# Generated by Django 4.0.4 on 2022-05-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_note_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date_time',
        ),
    ]
